// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMoECYWN-aHod0h5K_McHhn0aTi7khSss',
    appId: '1:190349280025:web:53277dd8e2709c10937b88',
    messagingSenderId: '190349280025',
    projectId: 'thunt-79e7b',
    authDomain: 'thunt-79e7b.firebaseapp.com',
    databaseURL: 'https://thunt-79e7b-default-rtdb.firebaseio.com',
    storageBucket: 'thunt-79e7b.appspot.com',
    measurementId: 'G-JZR7GV7PXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmun71qlnQojNWl3Rjm3Kd0YVrL1VlNsY',
    appId: '1:190349280025:android:691083ffeb6a1c94937b88',
    messagingSenderId: '190349280025',
    projectId: 'thunt-79e7b',
    databaseURL: 'https://thunt-79e7b-default-rtdb.firebaseio.com',
    storageBucket: 'thunt-79e7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr8mGKMKXweMd8_NbdmAU_SET9kStJKRs',
    appId: '1:190349280025:ios:bf3a3fdb22c544e0937b88',
    messagingSenderId: '190349280025',
    projectId: 'thunt-79e7b',
    databaseURL: 'https://thunt-79e7b-default-rtdb.firebaseio.com',
    storageBucket: 'thunt-79e7b.appspot.com',
    androidClientId: '190349280025-1d1mbvfvaa5stgc9uo0dgfs83psrhoud.apps.googleusercontent.com',
    iosClientId: '190349280025-k0aoa5ad7p1akd751euek4t4gfd1rlqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chopdirectDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr8mGKMKXweMd8_NbdmAU_SET9kStJKRs',
    appId: '1:190349280025:ios:bf3a3fdb22c544e0937b88',
    messagingSenderId: '190349280025',
    projectId: 'thunt-79e7b',
    databaseURL: 'https://thunt-79e7b-default-rtdb.firebaseio.com',
    storageBucket: 'thunt-79e7b.appspot.com',
    androidClientId: '190349280025-1d1mbvfvaa5stgc9uo0dgfs83psrhoud.apps.googleusercontent.com',
    iosClientId: '190349280025-k0aoa5ad7p1akd751euek4t4gfd1rlqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chopdirectDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXKpXad9z568uN3XwOjaKYsl-cC_6q4Hg',
    appId: '1:190349280025:web:dfc9ad52ace46253937b88',
    messagingSenderId: '190349280025',
    projectId: 'thunt-79e7b',
    authDomain: 'thunt-79e7b.firebaseapp.com',
    databaseURL: 'https://thunt-79e7b-default-rtdb.firebaseio.com',
    storageBucket: 'thunt-79e7b.appspot.com',
    measurementId: 'G-CWEXZ4VYCN',
  );
}
